<?php

return array(

    //  Day #    path             Title
    array('53',  'day053',        'Test for protected data elements'),
    array('52',  'day052',        'Pre-defined Carbon formats'),
    array('51',  'day051',        'Performance tests'),
    array('50',  'day050',        'Angular Image Upload'),
    array('49',  'day049',        'Ajax (jQuery) Image Upload'),
    array('48',  'day048',        'Image Upload'),
    array('47',  'day047',        'Angular Tabs'),
    array('46',  'day046',        'Form Validation'),
    array('45',  'day045',        'Ajax Forms (jQuery vs Angular)'),
    array('44',  'day044',        'File Uploading'),
    array('43',  'day043',        'Select2 Selection Controls'),
    array('42',  'day042',        'Bootstrap Forms 10 - FormBuilder Form Wizard'),
    array('41',  'day041',        'Bootstrap Forms 9 - FormBuilder Form Layout'),
    array('40',  'day040',        'Bootstrap Forms 8 - DRY Form Wizard'),
    array('39',  'day039',        'Bootstrap Forms 7 - Laravel / Bootstrap Form Wizard'),
    array('38',  'day038',        'Bootstrap Forms 6 - Nested Grids'),
    array('37',  'day037',        'Bootstrap Forms 5 - Former Form Layout'),
    array('36',  'day036',        'Bootstrap Forms 4 - Manual Form Layout'),
    array('35',  'day035',        'Bootstrap Forms 3 - Grid'),
    array('34',  'day034',        'Bootstrap Forms 2 - Form vs Form-Horizontal'),
    array('33',  'day033',        'Bootstrap Forms 1 - Manual vs FormBuilder Contact'),
    array('32',  'day032',        'Laravel Queued Mail'),
    array('31',  'day031',        'Option Group Splitter'),
    array('30',  'day030',        'D3 Test'),
    array('29',  'day029',        'Angular SVG'),
    array('28',  'day028',        'D3 Blocks'),
    array('27',  'day027',        'Angular List/Detail'),
    array('26',  'day026',        'Angular Todos'),
    array('25',  'day025',        'String Wrap Kata'),
    array('24',  'day024',        'Angular Show/Hide'),
    array('23',  'day023',        'Hello, Angular!'),
    array('22',  'day022',        'Prime Factors'),
    array('21',  'day021',        'Color Chart'),
    array('20',  'day020',        'Single Page Login'),
    array('19',  'day019',        'Date/Time Fields'),
    array('18',  'day018',        'Autocomplete (AJAX)'),
    array('17',  'day017',        'Field Types'),
    array('16',  'day016',        'Bowling Game Kata'),
    array('15',  'day015',        'Diamond Kata'),
    array('14',  'day014',        'Laravel Str Class Results'),
    array('13',  'day013',        'Image Cropping III'),
    array('12',  'day012',        'Image Cropping II'),
    array('11',  'day011',        'Image Cropping'),
    array('10',  'day010',        'Playing with CSS'),
    array('9',   'day009',        'Repository Todo'),
    array('8',   'day008',        'RESTful Todos'),
    array('7',   'day007',        'Todo List'),
    array('6',   'day006',        'View Composer'),
    array('5',   'day005_login',  'Login via Google'),
    array('4',   'day004_login',  'Login'),
    array('3',   'roman2',        'Roman Revisited'),
    array('2',   'roman',         'Roman Numerals'),
    array('1',   '',              'Homepage'),        

);
